### PR TITLE
See games with missing information

### LINKED ISSUE #93: All Games with No pictures / descriptions
The directors want to be able to see all of the games that have no pictures or have no descriptions in one place so they can go in and edit them.

Create the backend request to get all of these games
Create a button in the All Games page that shows up only when an admin is authenticated
When pressed, this button will show all games without descriptions and all games without pictures

### PR DESCRIPTION
**Pull request by arpanlaha**
Resolves #93

### CODE REVIEW

**Review by angadgarg25 — CHANGES_REQUESTED** [review]
image
Why is the second game here? We don't need to check if its missing the thumbail image if thats the reason.

**Review by angadgarg25 — APPROVED** [review]
Nvm, re-rending issue, looks fine 🐓

**Review by angadgarg25 — CHANGES_REQUESTED** [review]
The dropdown is messed up on this branch but not on master. (see image above)

**Review by hanarimawi — CHANGES_REQUESTED** [review]
Same issue as angads pic

**Review by angadgarg25 — APPROVED** [review]
🐓 ?

**Review by hanarimawi — APPROVED** [review]

**Pull request merged**
